dist: trusty
language: cpp
env:
 - OS=linux
 - OS=android
before_install:
 - cd lib && git submodule update --init && cd ..
 - if [ $OS = linux ]; then sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty && sudo apt-get update -qq && sudo apt-get install -y --force-yes qt54base qt54declarative qt54quickcontrols; fi
install:
 - if [ $OS = linux ]; then source /opt/qt54/bin/qt54-env.sh && qmllint client/qml/*.qml && make tensor; fi
 - if [ $OS = android ]; then make tensor.apk; fi
script: true
